site_name: Toward a new CCP for Arts, Humanities, and Culture research (CCP-AHC)
site_url: https://www.ccpahc.ac.uk
repo_url: https://github.com/ccpahc/ccpahc.github.io
repo_name: ccpahc/ccpahc.github.io
edit_uri: edit/main/docs/

theme:
    name: material
    palette:
        scheme: default
        primary: blue grey
    custom_dir: overrides
    features:
        - navigation.tracking
        - navigation.indexes
        - navigation.sections
        - navigation.tabs
        - search.suggest
        - content.action.edit
        - content.action.view
        - announce.dismiss

markdown_extensions:
    - admonition
    - attr_list
    - toc:
        permalink: "¶"
plugins:
    - blog
    - search
    - rss:
        match_path: blog/posts/.* 
        date_from_meta:
            as_creation: date
        categories:
            - categories
            - tags
    - git-revision-date-localized:
        enable_creation_date: true

extra:
  analytics:
    provider: google
    property: G-42ND01ZW5N

nav:
  - Home: index.md
  - About: about.md
  - Activities:
      - activities/index.md
      - CCP-AHC Expression of Interest for Research Software: activities/codes-eoi.md
      - CCP-AHC Town Hall 2025:
            - activities/town-hall-2025/index.md
            - Agenda: activities/town-hall-2025/agenda.md
  - Blog: blog/index.md
  - Resources:
      - UK HPC User Documentation Sites: resources/sites.md
