site_name: Toward a new CCP for Arts, Humanities, and Culture research (CCP-AHC)
site_url: https://ccpahc.github.io
repo_url: https://github.com/ccpahc/ccpahc.github.io
repo_name: ccpahc/ccpahc.github.io
edit_uri: edit/main/docs/

theme:
    name: material
    palette:
        scheme: default
        primary: blue grey
    features:
        - navigation.tracking
        - navigation.indexes
        - navigation.tabs
        - navigation.sections
        - search.suggest
        - content.action.edit
        - content.action.view

markdown_extensions:
    - attr_list
    - toc:
        permalink: "¶"
plugins:
    - blog
    - search
    - rss:
        match_path: blog/posts/.* 
        date_from_meta:
            as_creation: date
        categories:
            - categories
            - tags
    - git-revision-date-localized:
        enable_creation_date: true
extra:
  analytics:
    provider: google
    property: G-42ND01ZW5N