authors:
  eamonn:
    name: Eamonn Bell
    description: Project Lead
    avatar: https://avatars.githubusercontent.com/u/4513526
  sjmf:
    name: Samantha Finnigan
    description: Advanced Research Computing, Durham University
    avatar: https://avatars.githubusercontent.com/u/1038320